### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TBog** [kennethnym/StarlightLauncher#27]
Creative Commons [recommends](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) and [uses](https://opensource.creativecommons.org/) free and open source software licenses for software. [citation](https://creativecommons.org/about/program-areas/software/)

From [CC FAQ](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software)
We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available.

**Comment by kennethnym** [comment]
Thanks for pointing it out! I have updated the license to GPLv3.
