### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [kennethnym/StarlightLauncher#30]
Hi,

Since this app is GPLv3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app in F-Droid by yourself, would you still agree with the inclusion of your app in F-Droid by the maintainer team?

Could you please in the meantime tag your [releases](https://github.com/kennethnym/StarlightLauncher/releases) and attach a signed release apk to it, so that people can easily download your app?

**Comment by kennethnym** [comment]
Yes, I am planning to release it on FDroid for the next version. The froid releases will be full unlocked version unlike the play store version.

The next version will take a while because of migration to datastore and implementing an app drawer which a lot of people have requested.

**Comment by kennethnym** [comment]
@Poussinou I have created an [issue](https://gitlab.com/fdroid/rfp/-/issues/2182) to include Starlight Launcher in F-Droid's repo!
