### ISSUE TITLE
Idea for an App Drawer

### ISSUE THREAD

**Issue by EliotAku** [kennethnym/StarlightLauncher#56]
I made a mockup for a possible implementation of an app drawer. What do you think of it?
The drawer icon does the same thing as taping on the search bar (show app drawer, open keyboard, and focus search bar). 
![image](https://user-images.githubusercontent.com/54034023/202508833-57569166-487b-47f6-894f-3ae7aa7a6702.png)

**Comment by kennethnym** [comment]
Wow, that's amazing! I originally plan to implement the app drawer as a list that you can access by swiping left when you're on the home screen. However, I find that it interferes with the existing swipe gestures too much. I honestly much prefer your design to what I have at the moment. One question - when you perform search in the app drawer, should it search only in the app drawer, or should it perform a global search like normal?

**Comment by EliotAku** [comment]
Thank you, happy that you like the idea! It should do a global search because the app drawer is just a grid with all apps, shown when the search bar is focused without any text input. 
We access the app drawer just by taping the search bar, the drawer icon is only an indicator that there is an app drawer.
(Sorry for the closed/reopened, I missclicked...)

**Comment by kennethnym** [comment]
I see, that's also easier to implement as well from a coding point of view. Another minor question - in the mockup I see that the grid of apps are behind a plate. Would you say it's better if the background is fully blurred/covered, or would you prefer what you have in the mockup, i.e. the grid of apps are behind a plate like other widgets/search results for consistency's sake?

**Comment by EliotAku** [comment]
Mmmh, I'm not sure about that, but I think it's better like in my mockup. Because, yes, first for consistency, but also for a simpler transition when start to search. But yeah, the downside is that there is less horizontal space for apps icons then...
But maybe I'm wrong I don't know, what would you think is better?

**Comment by EliotAku** [comment]
Here is a quick example of how it could look like without blurred card.
![image](https://user-images.githubusercontent.com/54034023/202785545-aabac4e3-39aa-4332-96d3-d0e5795d91a6.png)

**Comment by kennethnym** [comment]
I like it! I prefer this to the card design. I will put this on the backlog.

**Comment by kennethnym** [comment]
@EliotAku I appreciate your mockup, but I ended up on a list design for the app drawer. This is a video demo

[Starlight Launcher app drawer demo.webm](https://user-images.githubusercontent.com/19359984/232163035-f82cc775-9e22-4dd5-b797-b2774e5b2ce7.webm)


It will be available in the next update. I hope you like it!
