### ISSUE TITLE
Widgets not adapting correctly to dark mode.

### ISSUE THREAD

**Issue by Rom1-GoPlay** [kennethnym/StarlightLauncher#77]
Hello, I just installed Starlight Launcher and I really like it !

But when I switch dark/light mode, widgets keep their colors.

For exemple, on this screenshot, you can see two Firefox search bars. One is white (added when dark mode was disabled) and the other is dark (because dark mode was enabled when I added it).
![widgetsThemeStarlight.jpg](https://github.com/kennethnym/StarlightLauncher/assets/131159819/4e353748-075f-4c90-83b5-a06c759b83ee)

I expect widgets to change colors when I switch dark mode.

**Comment by kennethnym** [comment]
Thanks for letting me know. I will look into it.

**Comment by kennethnym** [comment]
Fixed in e882025. Will be available in the next update.
