### ISSUE TITLE
Is this app dead? [Spoiler: No!]

### ISSUE THREAD

**Issue by privacyfreak84** [kennethnym/StarlightLauncher#78]
Is this app dead? I hope it's development continues

**Comment by kennethnym** [comment]
I would love to continue the development of this launcher. As I have other priorities right now, unfortunately I am not able to spend time on this as much as I'd like to.

However, this does not mean that Starlight is abandoned. I will work on Starlight when time allows so. Expect stability as the primary goal for the next release. However, I will not be able to provide a concrete timeline on when it will be released.

Hope this clarifies everything!

**Comment by privacyfreak84** [comment]
Well that's great to hear! Looking forward to the next release, whenever it may be

**Comment by kennethnym** [comment]
I appreciate your support of the launcher!
